### ISSUE TITLE
Move current (Java) code to a /src/ folder

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots-5604/2015-Code#6]
If we are using java this year, the code will be better kept if all Java code is contained inside a /src/ folder, and it will be much easier to work with Eclipse (which we should all be doing!). Eclipse does this by default, and it is possible to work around, but also difficult. We can leave the /legacy/ folder out of /src/, because it is not Java code and does not apply anymore.

**Comment by ZachOhara** [comment]
Resolved

**Comment by danielgrimshaw** [comment]
We will be using Android Studio, Android is no longer supporting Eclipse.

**Comment by ZachOhara** [comment]
This depends very heavily on what type of system FTC ends up releasing. Their goal is to make a system that everyone, *especially* novices, can use easily. I doubt they'd release something that requires interfacing directly with the Android OS, because that can get complicated and most of the programmers in the league probably would never be able to figure it out. If we don't have to use any of the features of the Android OS directly, we'll probably be very safe using Eclipse.

All being said, for non-Android Java development, Eclipse is much better than Android Studio. We should, for now, continue to optimize for Eclipse, and we can revisit this when the league releases more information.

**Comment by danielgrimshaw** [comment]
FTC has already announced that they are going to release a version of MIT App Inventor for the platform and that all of the advanced programming will be done from Android Studio. Eclipse is not going to be supported.

**Comment by ZachOhara** [comment]
Android Studio has a /src/ folder.
